name: Release package

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'master'
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set release version and deploy xbrl-accrual
        run: |
          mvn -B versions:set \
            -DnewVersion=${{ github.event.release.tag_name }} \
            -DgenerateBackupPoms=false

          mvn clean deploy \
            -s .m2/settings.xml \
            -DskipTests \
            --batch-mode \
            --errors \
            --fail-at-end \
            --show-version
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{  secrets.ISS_PAT }}

      - name: Update version in pom.xml width SNAPSHOT version
        run: |
          mvn -B versions:set \
            -DnewVersion=${{ github.event.release.tag_name }}-SNAPSHOT \
            -DgenerateBackupPoms=false
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push SNAPSHOT version
        run: |
          git config --global user.email "dirgensa@iss.it"
          git config --global user.name "dirgensa"

          git add pom.xml
          git commit -m "Bumped version to ${{ github.event.release.tag_name }}-SNAPSHOT" || echo "No changes to commit"
          git push origin xbrl-accrual
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}